version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - '5678:5678'
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    environment:
      - GENAI_EXECUTOR_TYPE=local

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./temp_outputs:/app/temp_outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: rocm
              capabilities: [gpu]
    # Keep the container running to execute commands into it
    command: tail -f /dev/null
